### PR TITLE
support batch_norm

### PR DESCRIPTION
**Pull request by hojel**
I add a function to support batch normalization layer included in the recent darknet models.
There ware two ways to include batch norm layer in darknet. One is batch_norm layer and the other one is batch_normalization feature in convolutional layer. This update support only the second one, which is more common.
I also remove channel swap for input data. Darknet uses RGB order, not BGR in Caffe.

### CODE REVIEW

**Comment by xingwangsfu** [comment]
Thanks @hojel . That's exactly what I plan to do.  Actually, I tried the second approach you mentioned. Although in my setup, the number of params in yolo matched the one in caffe model, the result seemed to be incorrect. Maybe there is something missing in my setup. Can you provide some tests to show the result from the converted caffe model matches the one from yolo? If that is the case, I'll definitely merge this.

**Comment by hojel** [comment]
yolo is fast changing and not easy to catch up.
You can download weights file I used in testing from [here](https://dl.dropboxusercontent.com/u/734336/tiny-yolo-model.zip).
I ran the following commands with this file.
```Shell
python create_yolo_caffemodel.py -m prototxtl/yolo_tiny_deploy.prototxt -w model/tiny-yolo.weights -o model/tiny-yolo.caffemodel
python yolo_main.py -m prototxt/yolo_tiny_deploy.prototxt -w model/tiny-yolo.caffemodel -i images/person.jpg
```

**Comment by Banus** [comment]
I tested it with the last [tiny-yolo](http://pjreddie.com/media/files/tiny-yolo.weights) model on `images/dog.jpg`. The confidences seems to be within rounding error, the predicted boxes off by a few pixels at the worst. I modified `Darknet` in order to output the coordinates.

Caffe-yolo:

    class : car , [x,y,w,h]=[569,124,249,95], Confidence = 0.574348688126
    class : dog , [x,y,w,h]=[204,386,235,332], Confidence = 0.267554342747

Darknet:

    car: 57%  [570.171631 123.604752 247.809677 93.684402]
    dog: 27% [203.111252 385.901489 236.291595 337.033600]

**Comment by AlexofNTHU** [comment]
@xingwangsfu : I use the YOLO (not YOLO_small or YOLO_tiny) caffemodel converted by you to run yolo_main.py. Then, I analyze the mAP using the standard VOC07 metric. I guess there were something wrong. The mAP of VOC07 test reported by YOLO's paper is 0.634 but yours is 0.401.

 Th AP of each class is 
[0.52855669154073437, 0.44539979238253113, 0.42508280603515264, 0.37113279810265537, 0.15082644628099173, 0.5278122843340235, 0.53235549892423506, 0.59468597663502099, 0.22648370497427103, 0.33484685740324838, 0.41921988304967034, 0.42398673071757581, 0.44726369848958925, 0.35008825609688649, 0.42000598018625906, 0.16927899686520376, 0.3569844789356984, 0.42856115403583761, 0.53118330333520203, 0.3376863787822692] .

The analysis python file is definitely correct because it is provided in Faster R-CNN.
How much mAP did you achieve using the model you provided?
Thanks

Alex

**Comment by xingwangsfu** [comment]
Thanks, @hojel, for your effort . I'll merge it. Also, thanks, @Banus and @AlexofNTHU  for your tests.

**Comment by AlexofNTHU** [comment]
@xingwangsfu  
I tried to follow your latest instruction
1. download yolo.cfg and the latest create_yolo_prototxt.py. execute the following command
 python create_yolo_prototxt.py yolo.cfg yolo.prototxt
2. download yolov1.weights and use the latest create_yolo_caffemodel.py and the yolo.prototxt created in the last step to generate its corresponding caffemodel. The command is 
python create_yolo_caffemodel.py -m yolo.prototxt -w yolov1.weights -o yolo.caffemodel

However, there is an error message after 2. I also tried yolo-tiny. The error message is the same.

```
fc25(fc)
Traceback (most recent call last):
  File "create_yolo_caffemodel.py", line 114, in <module>
    main(sys.argv[1:])
  File "create_yolo_caffemodel.py", line 93, in main
    net.params[pr][0].data[...] = np.reshape(netWeights[count:count+weightSize], dims)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged
```
@hojel , I downloaded the files in #14 . The conversion was successful but there is no detection result from the converted caffemodel and prototxt.

I really want to try caffe-yolo. Any suggestion is appreciated.
Thanks

Alex

>

**Pull request merged**
